name: Rasa CI

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
      - rasa_env
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  # Validate the Rasa data, e.g. check whether the same example
  # is used for 2 different intents, etc.
  data-validation:
    name: Validate Data
    runs-on: ubuntu-latest
    env:
      working-directory: ./Rasa_Bot
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Rasa_Bot/requirements.txt
    # The number for max-history needs to be adapted based on config.yml
    - name: Rasa Data Validation
      run: | 
        cd Rasa_Bot
        rasa telemetry disable
        import yaml
        f = open("config.yml")
        config_dict = yaml.load(f)
        hist = max([a['policies'][i]['max_history'] for i in range(len(a['policies'])) if not a['policies'][i]['name'] == 'RulePolicy'])
        f.close()
        rasa data validate --max-history hist
  training-testing:
    name: Train and Test model
    runs-on: ubuntu-latest
    needs: 
    - data-validation
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Rasa_Bot/requirements.txt
        rasa --version
    - name: Train model
      run: |
        cd Rasa_Bot
        rasa train
    - name: Test End 2 End Stories
      run: |
        cd Rasa_Bot
        rasa --version
        rasa test core --stories tests/test_conversations.yml --fail-on-prediction-errors
    # In the future, we could also save the trained model in github
    # See here for an example: https://github.com/RasaHQ/financial-demo/blob/db/.github/workflows/build_and_deploy.yml
   