name: Rasa CI

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
      - rasa_env
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  # Validate the Rasa data, e.g. check whether the same example
  # is used for 2 different intents, etc.
  data-validation:
    name: Validate Data
    runs-on: ubuntu-latest
    env:
      working-directory: ./Rasa_Bot
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Rasa_Bot/requirements-dev.txt
    # The number for max-history needs to be adapted based on config.yml
    - name: Get max history from config
      id: hist
      run:
        echo "::set-output name=hist::$(python rasa_get_max_history.py)"
    - name: Print hist
      run: 
        echo "${{ steps.hist.outputs.hist}}"
    - name: Rasa Data Validation
      run: |
        cd Rasa_Bot
        rasa telemetry disable
        rasa data validate --max-history $HIST
      env:
        HIST: ${{ steps.hist.outputs.hist }}
  training-testing:
    name: Train and Test model
    runs-on: ubuntu-latest
    needs: 
    - data-validation
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Rasa_Bot/requirements.txt
        rasa --version
    - name: Train model
      run: |
        cd Rasa_Bot
        rasa train
    - name: Test End 2 End Stories
      run: |
        cd Rasa_Bot
        rasa --version
        rasa test core --stories tests/test_conversations.yml --fail-on-prediction-errors
    # In the future, we could also save the trained model in github
    # See here for an example: https://github.com/RasaHQ/financial-demo/blob/db/.github/workflows/build_and_deploy.yml
   